apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-report
spec:
  selector:
    matchLabels:
      app: lab-report
  replicas: 1
  template:
    metadata:
      labels:
        app: lab-report
    spec:
      containers:
        - name: lab-report
          image: labreport:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
